spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/myticket_db
    username: postgres
    password: password
  liquibase:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false